spring.application.name=procedure-gateway



spring.datasource.url=jdbc:oracle:thin:@10.145.1.235:1522:rundb1
spring.datasource.username=HRIS_DEVP
spring.datasource.password=hrisdb@1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.thymeleaf.cache=false

#
server.port=8086
#server.servlet.context-path=/proceduregateway